### ISSUE TITLE
Search problems

### ISSUE THREAD

**Issue by senky** [phpbb/quickinstall#107]
Not sure why but posts generated by QI are malformed when searched for:
![img](https://user-images.githubusercontent.com/182498/53966458-80952780-40f3-11e9-9e05-6aa6eb3eedf6.png)
note `<t>` and `<br>`.

**Comment by VSEphpbb** [comment]
How are you able to search for "test"? None of the search indexes, which are all fulltext, should find the word "test" because it's too common, and an ignore word as well.

In a vanilla QI install I can't search for anything in any of the test posts because of fulltext's restrictions on common and frequently used words. So I can only search for words in the default welcome post, and in those, the results are not malformed:
![screen shot 2019-03-07 at 6 12 59 pm](https://user-images.githubusercontent.com/303711/54002791-ab3bac00-4104-11e9-9789-8ffeb62d0238.png)

So, what are yoy doing different?:)

**Comment by VSEphpbb** [comment]
OK, well I set the common word search setting off, and deleted and recreated the search index and now I see it too... But not really sure what to do about it. Don't really care about it, but also I only created the problem by messing with the forum itself, not QI, so, maybe it's more of a phpBB thing.

**Comment by 3D-I** [comment]
Click on "search user's posts" from the profile of a **tester_xx**, to reproduce.

That's on a fresh QI's install.

The solution, I mean is not an hack nor code, it is shortening the string in $lorem_ipsum. Then the new installation will not have such issue.

`$lorem_ipsum = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.';`

**Comment by VSEphpbb** [comment]
Well, trying to shorten it to a point where the results are not truncated isn't really solving it.

But it's only an issue with the pre-populated fake posts so not a big deal at all IMO.

**Comment by 3D-I** [comment]
More a workaround than a solution indeed. After 2 hours of code reading / attempts I gave up though.
And yes, not a big deal.

**Comment by VSEphpbb** [comment]
I see why this is happening. No clue how to deal with it though, as it's rooted in how phpBB works.

It's because all the posts created have no BBCODE_UID. But they have no BBCODE_UID because `generate_text_for_storage` won't create one for them, because there is also no BBCODE_BITFIELD.

But, if I go in my database, add a BBCODE_UID value to a post, then it appears correctly in the search result...

**Comment by senky** [comment]
But bbcode_uid shouldn't be used anymore with new textformatter, isn't that right?

**Comment by VSEphpbb** [comment]
I have no clue. When I look in the DB, some posts have them. And some don't.

**Comment by senky** [comment]
Got this! The problem is that it doesn't have `bbcode_bitfield`. Search then considers it a plaintext and won't remove BBcodes. I will post a fix soon.

**Comment by VSEphpbb** [comment]
Fixed here https://github.com/phpbb/quickinstall/pull/110/commits/ecff71dcc706c997fd3d183c413142c5212dfcb1
